-- PRACTICE QUESTION #1
-- QS: CREATE A DATABASE FOR YOUR COLLEGE
-- CREATE A TABLE NAMED TEACHER TO STORE (id,name,subject,salary)

DROP DATABASE IF EXISTS COLLEGE;

CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE staff_info
(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    SUBJECT VARCHAR(30) NOT NULL,
    SALARY INT
);

INSERT INTO staff_info
VALUES
(1,"Alice Sagaya Mary","Mathematics",60000),
(2,"Anna Pappu","English",50000),
(3,"Pelitas","Science",70000),
(4,"Nobil Initha","English",100000);

-- Select staff whose salary is more that 50K
SELECT * FROM staff_info
WHERE SALARY > 50000;

-- RENAME THE SALARY COLUMN OF STAFF_INFO ABLE TO CTC
ALTER TABLE staff_info
CHANGE COLUMN SALARY CTC INT DEFAULT 10000;

-- UPDATE SALARY OF ALL STAFF BY GIVING THEM AN INCREMENT OF 25%
SET SQL_SAFE_UPDATES = 0;
UPDATE staff_info
SET CTC = CTC + CTC*0.25;

-- ADD A NEW COLUMN FOR STAFF CALLED CITY. THE DEFAULT CITY SHOULD BE "COIMBATORE".
ALTER TABLE staff_info
ADD COLUMN CITY VARCHAR(20) DEFAULT "Coimbatore";

-- DELETE CTC COLUMN FROM STAFF TABLE
ALTER TABLE staff_info
DROP COLUMN CTC;

SELECT * FROM staff_info;


